spring:
    application:
        name: api-ironfit-socios

    datasource:
        url: jdbc:oracle:thin:@ tu url
        username: tu usuario
        password: tu password
        driver-class-name: oracle.jdbc.OracleDriver

    jpa:
        database-platform: org.hibernate.dialect.OracleDialect
        hibernate:
            ddl-auto: validate
        show-sql: true

server:
    port: 21502